name: CI

on: push

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: yarn install
        run: yarn install --frozen-lockfile --check-files
      - name: build
        run: yarn build
      - name: run
        run: |
          export HOST_IP=$(ip route show | awk '/default/ {print $3}')
          echo "Host ip address: $HOST_IP"
          yarn start
